version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - graphviz-dev

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs