version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - sudo apt-get install graphviz graphviz-dev

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs