[tool.poetry]
name = "sphinx_autodoc_pydantic"
version = "0.1.0"
description = ""
authors = ["mansenfranzen <franz.woellert@gmail.com>"]
packages = [
  { include = "sphinxcontrib" }
]

[tool.poetry.dependencies]
python = ">=3.6.1"
Sphinx = ">=2.0"
pydantic = ">=1.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov
sphinx-rtd-theme = "^0.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
