[tool.poetry]
name = "autodoc_pydantic"
version = "1.2.0"
description = "Seamlessly integrate pydantic models in your Sphinx documentation."
authors = ["mansenfranzen <franz.woellert@gmail.com>"]
packages = [{ include = "sphinxcontrib" }]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mansenfranzen/autodoc_pydantic"
repository = "https://github.com/mansenfranzen/autodoc_pydantic"
documentation = "https://github.com/mansenfranzen/autodoc_pydantic"
keywords = ["sphinx", "pydantic", "autodoc", "documentation", "extension"]
classifiers = [
    "Framework :: Sphinx :: Extension",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation"
]
include = ["sphinxcontrib/autodoc_pydantic/css/autodoc_pydantic.css"]

[tool.poetry.dependencies]
python = "^3.6.1"
Sphinx = ">=3.4"
pydantic = ">=1.5"

sphinx-rtd-theme = { version = "^0.5.1", optional = true }
sphinx-tabs = { version = "^2", optional = true }
pytest = {version = "^6.0", optional = true }
pytest-cov = { version = "^2.0", optional = true }

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov-report term --cov-report xml:coverage.xml --cov=sphinxcontrib"

[tool.poetry.extras]
docs = ["sphinx-rtd-theme",
        "sphinx-tabs"]

dev = ["pytest",
       "pytest-cov",
       "sphinx-rtd-theme",
       "sphinx-tabs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
