name: ci
on: [push, pull_request]

jobs:


  test-development-versions-deps:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    environment: ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install tox
      - run: tox -e development
        continue-on-error: true
      - run: echo "Done"

  test-linter:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    environment: ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install tox
      - run: tox -e linter
