name: CI
on: push

jobs:
  ci:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        os: [ubuntu-18.04]
        pydantic_version: ["=~1.8", "=~1.7", "=~1.6", "=~1.5", "=~1.0", "@latest"]
        sphinx_version: ["=~3.5", "=~3.4", "@latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
      - name: Update required deps
        run: poetry add pydantic${{ matrix.pydantic_version }} sphinx${{ matrix.sphinx_version }}
      - name: Install packages
        run: poetry install
      - name: run pytest
        run: poetry run pytest
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
