name: ci
on: push

jobs:
  test-stable-versions:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: 3.6
            pydantic_version: "15"
            sphinx_version: "34"
          - python_version: 3.7
            pydantic_version: "16"
            sphinx_version: "34"
          - python_version: 3.8
            pydantic_version: "17"
            sphinx_version: "35"
          - python_version: 3.9
            pydantic_version: "18"
            sphinx_version: "35"
          - python_version: 3.9
            pydantic_version: "18"
            sphinx_version: "40"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - run: pip install tox
      - run: tox -e pydantic${{ matrix.pydantic_version }}-sphinx${{ matrix.sphinx_version }}

  test-latest-version-with-coverage:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    environment: ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install tox
      - run: tox -e latest
      - run: export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml

  test-development-versions-deps:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    environment: ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install tox
      - run: tox -e development
